GET http://localhost:5167/WeatherForecast
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic2V5aG11czEyMTIxMkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzZXlobXVzMTIxMjEyQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiYmYzYmE4NzktYzFlZS00NjA0LTkyNTMtYmVjNGY0Y2QxZTA4IiwiZXhwIjoxNjgxNTE5NzcxLCJpc3MiOiJodHRwczovL3Bicy5kaWNsZS5lZHUudHIiLCJhdWQiOiJodHRwczovL3Bicy5kaWNsZS5lZHUudHIifQ.zO0OTHnmGbvTxPlLWhPZsviMmpt3HTUVe9DUD8nlsjo


